# This file was *autogenerated* from the file diploma.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
k = _sage_const_5 
R = GF(k)['x, y']; (x, y,) = R._first_ngens(2)
flist, glist = [], []
var('f_n g_n')
#j = 1 - (y-x)^(k-1)
#p = j(0,x)*f_n + j(1,x)*g_n - j(2,x)*f_n - j(3,x)*g_n + j(4,x)*f_n

z1,z2 = GF(_sage_const_5 )['z1, z2'].gens()
print '$ f_{n+1} = j_0(x_{n+1})f_n + j_1(x_{n+1})g_n - j_2(x_{n+1})f_n - j_3(x_{n+1})g_n + j_4(x_{n+1})f_n'
for i in range(k):
    z1 = z2 - i
    p = (_sage_const_1 -z1**(k-_sage_const_1 ))*f_n + (_sage_const_1 -(z1-_sage_const_1 )**(k-_sage_const_1 ))*g_n - (_sage_const_1 -(z1-_sage_const_2 )**(k-_sage_const_1 ))*f_n - (_sage_const_1 -(z1-_sage_const_3 )**_sage_const_4 )*g_n + (_sage_const_1 -(z1-_sage_const_4 )**_sage_const_4 )*f_n
    flist.append(p.expand().collect(z2).subs(z2=x+i))
    print ' = ' + latex(flist[i]).replace('x','x_{n+1}')
print '$\n'

print '$ g_{n+1} = j_0(x_{n+1})g_n - j_1(x_{n+1})f_n - j_2(x_{n+1})g_n + j_3(x_{n+1})f_n + j_4(x_{n+1})g_n'
for i in range(k):
    z1 = z2 - i
    p = (_sage_const_1 -z1**(k-_sage_const_1 ))*g_n - (_sage_const_1 -(z1-_sage_const_1 )**(k-_sage_const_1 ))*f_n - (_sage_const_1 -(z1-_sage_const_2 )**(k-_sage_const_1 ))*g_n + (_sage_const_1 -(z1-_sage_const_3 )**_sage_const_4 )*f_n + (_sage_const_1 -(z1-_sage_const_4 )**_sage_const_4 )*g_n
    glist.append(p.expand().collect(z2).subs(z2=x+i))
    print ' = ' + latex(glist[i]).replace('x','x_{n+1}')
print '$\n'

# #s = ''
# print flist[0]
# print '\n'.join([' + '.join([str(flist[0].coeff(x,j) * i^j) for j in range(k-1,-1,-1)]) +' = '+str(flist[0](x=i)) for i in range(k)])
'''
for i in range(k):
    strMyOne = ''
    for j in range(k):
        print flist[0].coeff(x,j) * i^j
    print strMyOne
'''
#print (flist[0] + glist[0]).collect(x)
